name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./gwc-website

      - name: Build frontend
        run: npm run build
        working-directory: ./gwc-website        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this if your resources are in a different region

      - name: Upload to S3
        run: |
          aws s3 sync ./test-site-for-hunter-kyle/dist/ s3://test-site-for-hunter-kyle/main --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID_STAGING }} \
            --paths "/*"

  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./gwc-website

      - name: Build frontend
        run: npm run build
        working-directory: ./gwc-website        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this if your resources are in a different region

      - name: Upload to S3
        run: |
          aws s3 sync ./test-site-for-hunter-kyle/dist/ s3://test-site-for-hunter-kyle/production --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID_PRODUCTION }} \
            --paths "/*"
